# Query to retrieve all repositories for a user - 50 items per page
#
# "variables":{"queryString":"user:barrettotte is:public", "after": "<end-cursor>"}
#
query($queryString: String!, $after: String) {
  search(type: REPOSITORY, query: $queryString, after: $after, first: 50) {
    repositoryCount
    pageInfo {
      startCursor
      hasNextPage
      endCursor
    }
    edges {
      node {
        ... on Repository {
          name
          stargazers {
            totalCount
          }
          forkCount
          languages(first: 3, orderBy: {field: SIZE, direction: DESC}) {
            nodes {
              name
              color
            }
          }
        }
      }
    }
  }
}